name: GitHub Actions Saucedemo
on: [push]
jobs:
  GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3
      - name: Setup Python             #github actions marketplace > setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Black and flake8          # >python lint>Python Code Quality and Lint
        uses: ricardochaves/python-lint@v1.4.0
        with:
          python-root-list: ""
          use-pylint: false
          use-pycodestyle: false
          use-flake8: true
          use-black: true
          use-mypy: false
          use-isort: false
          extra-pylint-options: ""
          extra-pycodestyle-options: ""
          extra-flake8-options: "--count --benchmark --ignore=E501,F401,F403,F405,W503"
          extra-black-options: ". -S"
          extra-mypy-options: ""
          extra-isort-options: ""
