name: GitHub Actions Saucedemo
on:
  pull_request:
    branches: [ "main" ]
    
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3
        
      - name: Setup Python             #github actions marketplace > setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install flake8 pytest
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi 
            
      - name: Run tests
        run: |
          pytest -s -v
          
      - name: Загрузка отчета
        uses: actions/upload-artifact@v2
        with:
          name: test-report
          path: report.html
